### ISSUE TITLE
Configuration bugged and have 1 and half config file in alacritty.yml

### ISSUE THREAD

**Issue by Spleenftw** [egeesin/alacritty-color-export#3]
I sometimes just reload my awesome, which is changing the background and the alacritty color then.

Sometimes it does change the color but put the config in double with one or two lines missing and that makes the entire alacritty config bug :

example : 

```
# BEGIN ACE
colors:
  primary:
    background: '#170806'
    foreground: '#8b8382'
  cursor:
    text:       '#170806'
    cursor:     '#8b8382'
  normal:
    black:      '#170806'
    red:        '#be8685'
    green:      '#be9387'
    yellow:     '#ab8290'
    blue:       '#be8d92'
    magenta:    '#bf9a9d'
    cyan:       '#bfa8a3'
    white:      '#8b8382'
  bright:
    black:      '#514544'
    red:        '#FEB3B2'
    green:      '#FEC5B5'
    yellow:     '#E4AEC1'
    blue:       '#FEBDC3'
    magenta:    '#FFCED2'
    cyan:       '#FFE1DA'
    white:      '#c5c1c0'
font:
  size: 8
  offset:
    x: 0
    y: 1
window:
    opacity: 0.8
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true
selection:
  save_to_clipboard: true
cursor:
  style: Block
  unfocused_hollow: true
# END ACE primary:
    background: '#170806'
    foreground: '#8b8382'
  cursor:
    text:       '#170806'
    cursor:     '#8b8382'
  normal:
    black:      '#170806'
    red:        '#be8685'
    green:      '#be9387'
    yellow:     '#ab8290'
    blue:       '#be8d92'
    magenta:    '#bf9a9d'
    cyan:       '#bfa8a3'
    white:      '#8b8382'
  bright:
    black:      '#514544'
    red:        '#FEB3B2'
    green:      '#FEC5B5'
    yellow:     '#E4AEC1'
    blue:       '#FEBDC3'
    magenta:    '#FFCED2'
    cyan:       '#FFE1DA'
    white:      '#c5c1c0'
font:
  size: 8
  offset:
    x: 0
    y: 1
window:
    opacity: 0.8
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true
selection:
  save_to_clipboard: true
cursor:
  style: Block
  unfocused_hollow: true
# END ACE
```

EDIT : it's just that the primary go next to the END instead of going one down.

**Comment by egeesin** [comment]
Sorry, can you give details about this part?

> Sometimes it does change the color but put the config in double with one or two lines missing

Also do you have access to older version of your config so I can check if there's something wrong?

**Comment by Spleenftw** [comment]
Hello, i used the basic dracula colorscheme : 

```
# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Template
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

colors:
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'
    bright_foreground: '#ffffff'
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: '#44475a'
      background: '#50fa7b'
    focused_match:
      foreground: '#44475a'
      background: '#ffb86c'
    bar:
      background: '#282a36'
      foreground: '#f8f8f2'
  hints:
    start:
      foreground: '#282a36'
      background: '#f1fa8c'
    end:
      foreground: '#f1fa8c'
      background: '#282a36'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: '#44475a'
  normal:
    black: '#21222c'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#bd93f9'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#f8f8f2'
  bright:
    black: '#6272a4'
    red: '#ff6e6e'
    green: '#69ff94'
    yellow: '#ffffa5'
    blue: '#d6acff'
    magenta: '#ff92df'
    cyan: '#a4ffff'
    white: '#ffffff'
```

But it seems like it deleted what was written in the alacritty.yml (don't really care since i can find it on the net).

**Comment by Spleenftw** [comment]
I'm recording the behavior so you can see what's happening.

EDIT : here's the video : https://www.youtube.com/watch?v=1SV8bQGSi7g

**Comment by egeesin** [comment]
In the beginning of the video, `# BEGIN ACE` is in the line 1 and this is unintended since `# BEGIN ACE` and `# END ACE` supposed to surround only color related configurations as seen in README example, not all configurations.

If there isn't BEGIN/END comments (in other words, if this is your first time running this script), script should *append* these color configs generated by pywal without modifying existing Alacritty configs.

Was that `# BEGIN ACE` generated by the script in the line 1 at the first place?

**Comment by Spleenftw** [comment]
```
Was that # BEGIN ACE generated by the script in the line 1 at the first place?
```

Yes

**Comment by egeesin** [comment]
> Hello, i used the basic dracula colorscheme :
> 
> ```
> # Dracula theme for Alacritty
> # https://draculatheme.com/alacritty[](https://draculatheme.com/alacritty)
> #
> # Color palette
> # https://spec.draculatheme.com[](https://spec.draculatheme.com)
> #
> # Template
> # https://github.com/alacritty/alacritty/blob/master/alacritty.yml[](https://github.com/alacritty/alacritty/blob/master/alacritty.yml)
> 
> colors:
>   primary:
>     background: '#282a36'
>     foreground: '#f8f8f2'
>     bright_foreground: '#ffffff'
>   cursor:
>     text: CellBackground
>     cursor: CellForeground
>   vi_mode_cursor:
>     text: CellBackground
>     cursor: CellForeground
>   search:
>     matches:
>       foreground: '#44475a'
>       background: '#50fa7b'
>     focused_match:
>       foreground: '#44475a'
>       background: '#ffb86c'
>     bar:
>       background: '#282a36'
>       foreground: '#f8f8f2'
>   hints:
>     start:
>       foreground: '#282a36'
>       background: '#f1fa8c'
>     end:
>       foreground: '#f1fa8c'
>       background: '#282a36'
>   line_indicator:
>     foreground: None
>     background: None
>   selection:
>     text: CellForeground
>     background: '#44475a'
>   normal:
>     black: '#21222c'
>     red: '#ff5555'
>     green: '#50fa7b'
>     yellow: '#f1fa8c'
>     blue: '#bd93f9'
>     magenta: '#ff79c6'
>     cyan: '#8be9fd'
>     white: '#f8f8f2'
>   bright:
>     black: '#6272a4'
>     red: '#ff6e6e'
>     green: '#69ff94'
>     yellow: '#ffffa5'
>     blue: '#d6acff'
>     magenta: '#ff92df'
>     cyan: '#a4ffff'
>     white: '#ffffff'
> ```
> 
> But it seems like it deleted what was written in the alacritty.yml (don't really care since i can find it on the net).

When I've this in my ``.config/alacritty/alacritty.yml`` and running the script I got this:
```sh
# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Template
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

colors:
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'
    bright_foreground: '#ffffff'
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: '#44475a'
      background: '#50fa7b'
    focused_match:
      foreground: '#44475a'
      background: '#ffb86c'
    bar:
      background: '#282a36'
      foreground: '#f8f8f2'
  hints:
    start:
      foreground: '#282a36'
      background: '#f1fa8c'
    end:
      foreground: '#f1fa8c'
      background: '#282a36'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: '#44475a'
  normal:
    black: '#21222c'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#bd93f9'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#f8f8f2'
  bright:
    black: '#6272a4'
    red: '#ff6e6e'
    green: '#69ff94'
    yellow: '#ffffa5'
    blue: '#d6acff'
    magenta: '#ff92df'
    cyan: '#a4ffff'
    white: '#ffffff'
# BEGIN ACE
colors:
  primary:
    background: '#180f18'
    foreground: '#cbc2e1'
  cursor:
    text:       '#180f18'
    cursor:     '#cbc2e1'
  normal:
    black:      '#180f18'
    red:        '#6A538E'
    green:      '#464AAB'
    yellow:     '#916A98'
    blue:       '#C569B5'
    magenta:    '#EBB0B2'
    cyan:       '#AD93D5'
    white:      '#cbc2e1'
  bright:
    black:      '#8e879d'
    red:        '#6A538E'
    green:      '#464AAB'
    yellow:     '#916A98'
    blue:       '#C569B5'
    magenta:    '#EBB0B2'
    cyan:       '#AD93D5'
    white:      '#cbc2e1'
# END ACE
```
As I said, the ACE block should append without modifying over existing configuration if you running it for the first time. But if there's existing # BEGIN ACE, # END ACE comments in the wrong place before the execution, this can corrupt the configuration file. I'm unable to reproduce your issue.

**Comment by Spleenftw** [comment]
So the normal behaviour should be :

base alacritty.yml :
```
font:
  size: 8
  offset:
    x: 0
    y: 1
window:
    opacity: 0.8
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true
selection:
  save_to_clipboard: true
cursor:
  style: Block
  unfocused_hollow: true

# BEGIN ACE
colors:
  primary:
    background: '#020204'
    foreground: '#808081'
  cursor:
    text:       '#020204'
    cursor:     '#808081'
  normal:
    black:      '#020204'
    red:        '#283455'
    green:      '#333f5a'
    yellow:     '#2b3766'
    blue:       '#3c4a73'
    magenta:    '#414987'
    cyan:       '#70516f'
    white:      '#808081'
  bright:
    black:      '#414142'
    red:        '#364672'
    green:      '#445579'
    yellow:     '#3A4A89'
    blue:       '#51639A'
    magenta:    '#5762B4'
    cyan:       '#966D94'
    white:      '#bfbfc0'
# END ACE
```

Launch the script.sh, and only the text between # BEGIN ACE and # END ACE should be switched with the new colors, right ?

Because the script is just removing this part and write the colors :

```
font:
  size: 8
  offset:
    x: 0
    y: 1
window:
    opacity: 0.8
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true
selection:
  save_to_clipboard: true
cursor:
  style: Block
  unfocused_hollow: true
```
